"""add retry_count to order

Revision ID: 32df381a20f2
Revises: 631233521f1f
Create Date: 2026-02-09 09:07:32.955237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32df381a20f2'
down_revision = '631233521f1f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('orders', schema=None) as batch_op:
        # 1. Cho phép NULL trước
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))

    # 2. Set default cho dữ liệu cũ
    op.execute("UPDATE orders SET retry_count = 0 WHERE retry_count IS NULL")

    # 3. Ép NOT NULL
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('retry_count', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('last_error')
        batch_op.drop_column('retry_count')

    # ### end Alembic commands ###
