"""empty message

Revision ID: 806f06d3f102
Revises: 7a0bc71b5c10
Create Date: 2026-02-23 14:19:36.422366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806f06d3f102'
down_revision = '7a0bc71b5c10'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'sent_tele',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('false')
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('sent_tele')

    # ### end Alembic commands ###
