"""empty message

Revision ID: 8e19f6d47ba9
Revises: f406e7671a1e
Create Date: 2026-02-06 09:29:04.807536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e19f6d47ba9'
down_revision = 'f406e7671a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PENDING', 'PROCESSING', 'CONFIRMED', 'SHIPPING', 'COMPLETED', 'CANCELLED', name='order_statuses'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'CONFIRMED', 'SHIPPING', 'COMPLETED', 'CANCELLED', name='order_statuses'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)

    # ### end Alembic commands ###
