"""empty message

Revision ID: ae7c64059b5a
Revises: 806f06d3f102
Create Date: 2026-03-06 11:38:49.509389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae7c64059b5a'
down_revision = '806f06d3f102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddd_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ddd_wallets_user_id'))

    op.drop_table('ddd_wallets')
    with op.batch_alter_table('ddd_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ddd_users_email'))
        batch_op.drop_index(batch_op.f('ix_ddd_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_ddd_users_role'))

    op.drop_table('ddd_users')
    with op.batch_alter_table('ddd_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ddd_order_items_product_id'))

    op.drop_table('ddd_order_items')
    with op.batch_alter_table('ddd_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ddd_products_is_active'))
        batch_op.drop_index(batch_op.f('ix_ddd_products_seller_id'))

    op.drop_table('ddd_products')
    with op.batch_alter_table('ddd_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ddd_orders_customer_id'))
        batch_op.drop_index(batch_op.f('ix_ddd_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_ddd_orders_seller_id'))
        batch_op.drop_index(batch_op.f('ix_ddd_orders_status'))

    op.drop_table('ddd_orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ddd_orders',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('order_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('shipping_address', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('shipping_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ddd_orders_pkey'))
    )
    with op.batch_alter_table('ddd_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ddd_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ddd_orders_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ddd_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_ddd_orders_customer_id'), ['customer_id'], unique=False)

    op.create_table('ddd_products',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ddd_products_pkey'))
    )
    with op.batch_alter_table('ddd_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ddd_products_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ddd_products_is_active'), ['is_active'], unique=False)

    op.create_table('ddd_order_items',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('processing_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('ddd_order_items_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ddd_order_items_pkey'))
    )
    with op.batch_alter_table('ddd_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ddd_order_items_product_id'), ['product_id'], unique=False)

    op.create_table('ddd_users',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ddd_users_pkey'))
    )
    with op.batch_alter_table('ddd_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ddd_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_ddd_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ddd_users_email'), ['email'], unique=True)

    op.create_table('ddd_wallets',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ddd_wallets_pkey'))
    )
    with op.batch_alter_table('ddd_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ddd_wallets_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###
