"""empty message

Revision ID: f406e7671a1e
Revises: fcc3812e0dc3
Create Date: 2026-02-05 11:48:07.339611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f406e7671a1e'
down_revision = 'fcc3812e0dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('processing_at')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('processing_at')

    # ### end Alembic commands ###
