"""empty message

Revision ID: fcc3812e0dc3
Revises: cc5023cfaa89
Create Date: 2026-02-04 14:11:38.519667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc3812e0dc3'
down_revision = 'cc5023cfaa89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', 'REFUNDED', 'COMPLETED', 'RESERVED', 'FAILED', 'REFUND_REQUESTED', name='order_item_statuses'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
